### ISSUE TITLE
Request : for creating anaglyph conversation 

### ISSUE THREAD

**Issue by unite-deals** [IlhamriSKY/Simple-DepthMap-3D-Animation#1]
Hey really cool about this app, could you please  create an option for anaglyph conversation, it will be exciting to watch in 3D.

**Comment by IlhamriSKY** [comment]
https://github.com/user-attachments/assets/accdbcf0-afb5-479d-9181-5b480d4c5545

Done

you can see new pull code here
https://github.com/IlhamriSKY/Simple-DepthMap-3D-Animation/pull/2

Will close this issue thanks for idea
